title: App
id: licences-app
theme: light
extra: licence
order: 3c
content:
  first: |
    This licence grants the use of fonts in applications to effectively display the content. In most cases, one must review the EULA to determine whether the licence covers desktop applications or is restricted to mobile software. The fonts are embedded in the app and loaded into the user interface.
  more: |
    The App licence is sometimes offered as App/ePub or App/Game. For foundries with a separate licence for games, we have observed that the metrics and pricing align with the App, so we have not made a separate analysis.

text: |
  There is a predominant measuring unit here, the number of apps that will include the font. We use the general term ‘use case’ instead, as it is appropriate for other licences too. Some other metrics are connected to who sees/reads/interacts with the app (downloads and monthly users), but, in this case, the percentage in the sample is smaller (19%) than in web licences.

  We have also identified five foundries that rely on the number of years as the only metric. The sample includes more non-perpetual licences for apps than for other purposes, with seven charging an annual subscription and eight imposing limits based on the number of years.

  The font licence cost for apps is often higher than that for web and desktop, sometimes doubling or even increasing tenfold. However, a few foundries maintain the same basic fee. The result is a broad range, with most foundries keeping their prices below 250€ for one text font.

chart:
  title: Popular measuring units in app licences
  key: app

chart_tiers:
  - title: Popular tiers for Number of Apps
    key: app-tiers-usecase
    units: [app, apps]
    description: |
      The number on the right indicates the amount of foundries that offer that particular tier. We show the 10 most popular tiers in the sample.
  - title: Popular tiers for Number of Monthly Users
    key: app-tiers-monthlyusers
    units: [user, users]
    description: |
      Three type foundries include an option for an unlimited number of monthly users. Counting all the different metrics for app use, a total of 27 offer an unlimited option.
  - title: Popular tiers for Number of Downloads
    key: app-tiers-downloads
    units: [download, downloads]
    description: |
      The lowest limit we have found is 50 app downloads; the highest value peaks at 1,000 million downloads.
pricing:
  title: Pricing in app licences
  key: app-pricing
